# Generated by Django 5.1.6 on 2025-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('insurance', models.CharField(blank=True, max_length=80)),
                ('situation', models.CharField(blank=True, max_length=120)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('solutions', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('financing', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('hipaa', models.BooleanField(default=False)),
                ('qualification_status', models.CharField(choices=[('qualified', 'Qualified'), ('nurture', 'Nurture'), ('disqualified', 'Disqualified')], default='nurture', max_length=20)),
                ('qualification_score', models.IntegerField(default=0)),
                ('qualification_reasons', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
