# Generated by Django 5.2.4 on 2025-08-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('insurance', models.CharField(blank=True, max_length=80)),
                ('situation', models.CharField(blank=True, max_length=120)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('symptoms', models.TextField(blank=True, default=list, max_length=60)),
                ('solutions', models.TextField(blank=True, default=list, max_length=60)),
                ('financing', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('hipaa', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True, default=list, max_length=40)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
