# Generated by Django 5.1.6 on 2025-08-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_lead_last_contact_lead_service_lead_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('delay_hours', models.IntegerField(default=0)),
                ('trigger_on', models.CharField(choices=[('qualified', 'Qualified'), ('nurture', 'Nurture'), ('disqualified', 'Disqualified')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='intake.lead')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.followuptemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='intake_foll_status_9f704b_idx')],
            },
        ),
    ]
