# Generated by Django 5.1.6 on 2025-08-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_followuptemplate_followupjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followuptemplate',
            old_name='delay_hours',
            new_name='delay_minutes',
        ),
    ]
